#!/bin/sh

# script run gui of hamagui
# in future it will install and then run script


# dir where situated gui.py
dir=$(pwd)/hamagui
file=gui.py
filepath=$dir/$file

echo $filepath
sudo python "$filepath"
